# syntax=docker/dockerfile:1

FROM node:20-alpine AS base

FROM base AS deps
RUN apk add --no-cache libc6-compat
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci

FROM base AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .

ARG NEXT_PUBLIC_WHATSAPP_PHONE
ARG NEXT_PUBLIC_WHATSAPP_PREFILL_MESSAGE
ARG NEXT_PUBLIC_VOICE_PHONE
ARG NEXT_PUBLIC_ENQUIRY_EMAIL
ARG NEXT_PUBLIC_ENQUIRY_SCRIPT_URL
ARG NEXT_PUBLIC_DOC_BROCHURE_PDF
ARG NEXT_PUBLIC_TOWNSHIP_FLYTHROUGH_SRC

ENV NEXT_PUBLIC_WHATSAPP_PHONE=$NEXT_PUBLIC_WHATSAPP_PHONE
ENV NEXT_PUBLIC_WHATSAPP_PREFILL_MESSAGE=$NEXT_PUBLIC_WHATSAPP_PREFILL_MESSAGE
ENV NEXT_PUBLIC_VOICE_PHONE=$NEXT_PUBLIC_VOICE_PHONE
ENV NEXT_PUBLIC_ENQUIRY_EMAIL=$NEXT_PUBLIC_ENQUIRY_EMAIL
ENV NEXT_PUBLIC_ENQUIRY_SCRIPT_URL=$NEXT_PUBLIC_ENQUIRY_SCRIPT_URL
ENV NEXT_PUBLIC_DOC_BROCHURE_PDF=$NEXT_PUBLIC_DOC_BROCHURE_PDF
ENV NEXT_PUBLIC_TOWNSHIP_FLYTHROUGH_SRC=$NEXT_PUBLIC_TOWNSHIP_FLYTHROUGH_SRC

ENV NEXT_TELEMETRY_DISABLED=1
RUN npm run build

FROM base AS runner
WORKDIR /app
ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1

RUN addgroup --system --gid 1001 nodejs && adduser --system --uid 1001 nextjs

COPY --from=builder /app/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs
EXPOSE 3000
ENV PORT=3000
ENV HOSTNAME=0.0.0.0

CMD ["node", "server.js"]
